config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path_names: { sign_in: :login, sign_out: :logout, sign_up: :signup }, controllers: {sessions: "sessions"}

  authenticated :user do
    root 'tests#index', as: :authenticated_root
  end

  unauthenticated :user do
    devise_scope :user do
      root 'sessions#new', as: :unauthenticated_root
    end
  end
  
  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[ show update ] do
    resources :gists, only: :create
    member do
      get :result
    end
  end

  resources :badges, only: :index

  namespace :admin do
    resources :gists, only: :index
    resources :badges, except: :show
    resources :tests do
      patch :update_inline, on: :member
      
      resources :questions, except: :index, shallow: true do
        resources :answers, shallow: true, except: :index
      end
    end
  end

  resources :feedbacks, only: %i[ index create ]

end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  validates :name, presence: true, uniqueness: true
  validates :image_url, :rule_type, :rule_value, presence: true
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :find_badge, only: %i[edit update destroy]

  def index
    @badges = Badge.all
  end

  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      redirect_to admin_badges_path
    else
      render :new
    end
  end

  def new
    @badge = Badge.new
  end

  def edit
  end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badges_path
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy

    redirect_to admin_badges_path
  end

  private
  def badge_params
    params.require(:badge).permit(:name, :description, :rule_type, :rule_value, :image_url)
  end

  def find_badge
    @badge = Badge.find(params[:id])
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController

  def index
    @badges = Badge.all
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td class="text-center"><%= badge.id %></td>
  <td class="text-center"><%= badge.name %></td>
  <td class="text-center"><%= badge.description %></td>
  <td class="text-center"><%= badge.rule_type %></td>
  <td class="text-center"><%= badge.rule_value %></td>
  <td class="text-center"><%= image_tag(badge.image_url, size: "100x100") %></td>
  <td class="text-center"><%= link_to t('actions.edit'), edit_admin_badge_path(badge) %></td>
  <td class="text-center">
    <%= link_to t('actions.delete'),
                admin_badge_path(badge),
                method: :delete,
                data: {confirm: t('actions.confirm')} %>
  </td>
</tr>

app/views/admin/badges/_form.html.erb
<%= form_with model: [:admin, @badge],
              class: 'form',
              local: true do |form| %>
  <%= render 'devise/shared/error_messages', resource: @badge %>

  <p>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :description %>
    <%= form.text_field :description %>
  </p>

  <p>
    <%= form.label :rule_type %>
    <%= form.text_field :rule_type %>
  </p>

  <p>
    <%= form.label :rule_value %>
    <%= form.text_field :rule_value %>
  </p>

  <p>
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </p>

  <p>
    <% if @badge.image_url != nil %> 
      <%= image_tag(@badge.image_url, size: "100x100") %>
    <% end %>
  </p>

  <%= form.submit %>

<% end %>

app/views/admin/badges/edit.html.erb
<div class="row">
  <h1><%= t('.header') %></h1>

  <%= render 'form' %>

  <%= link_to t('nav.back'), admin_badges_path %>
</div>

app/views/admin/badges/index.html.erb
<div class="row">
  <h1><%= t('.header') %></h1>

  <%= link_to t('.new_badge_link'), new_admin_badge_path %>
  <table class="table table-hover table-bordered">
    <thead>
      <tr>
        <th class="col text-center"><%= t('.id') %></th>
        <th class="col text-center">
          <%= t('.name') %>
        </th>
        <th class="col text-center"><%= t('.description')%></th>
        <th class="col text-center"><%= t('.rule_type')%></th>
        <th class="col text-center"><%= t('.rule_value')%></th>
        <th class="col text-center"><%= t('.image')%></th>
        <th class="col text-center" colspan="2"><%= t('.actions')%></th>
      </tr>
    </thead>

    <tbody>
      <%= render @badges %>
    </tbody>
  </table>
</div>

app/views/admin/badges/new.html.erb
<div class="row">
  <h1><%= t('.header') %></h1>

  <%= render 'form' %>

  <%= link_to t('nav.back'), admin_badges_path %>
</div>