config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path_names: { sign_in: :login, sign_out: :logout, sign_up: :signup }, controllers: {sessions: "sessions"}

  authenticated :user do
    root 'tests#index', as: :authenticated_root
  end

  unauthenticated :user do
    devise_scope :user do
      root 'sessions#new', as: :unauthenticated_root
    end
  end
  
  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[ show update ] do
    resources :gists, only: :create
    member do
      get :result
    end
  end

  resources :badges, only: :index

  namespace :admin do
    resources :gists, only: :index
    resources :badges, except: :show
    resources :tests do
      patch :update_inline, on: :member
      
      resources :questions, except: :index, shallow: true do
        resources :answers, shallow: true, except: :index
      end
    end
  end

  resources :feedbacks, only: %i[ index create ]

end

app/models/admin.rb
class Admin < User
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :validate_number_of_answers, on: :create

  scope :correct_answers, -> { where(correct: true) }

  private
  
  def validate_number_of_answers
    errors.add(:answers_count, 'limit is 4') unless question.answers.count < 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  validates :name, presence: true, uniqueness: true
  validates :image_url, :rule_type, :rule_value, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests, dependent: :destroy

  validates :title, presence: true

  default_scope { order(title: :asc) }
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test 
  
  has_many :answers, dependent: :destroy

  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  has_many :questions, dependent: :destroy
  
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages

  validates :title, :level, presence: true
  validates :level, numericality: { only_integer: true }
  validates :level, numericality: { greater_than_or_equal_to: 0 }
  validates :title, uniqueness: { scope: :level, case_sensitive: false }

  scope :easy, -> { where(level: 0..1) }
  scope :normal, -> { where(level: 2..4) }
  scope :hard, -> { where(level: 5..) }

  scope :find_test_by_category, -> (category) {
    joins(:category)
    .where(categories: {title: category})
  }

  def self.find_test_title_by_category(category)
    find_test_by_category(category).pluck('title')
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :set_current_question
  before_create :set_deadline

  SUCCESS_RATIO = 85

  def completed?
    deadline.nil? ? current_question.nil? : current_question.nil? || deadline.past?
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if !completed? && correct_answer?(answer_ids)
    save!
  end

  def current_question_number
    test.questions.order(:id).where('id < ?', current_question.id).size + 1
  end
  
  def percentage_score
    self.correct_questions.to_f / test.questions.count * 100
  end

  def success?
    percentage_score >= SUCCESS_RATIO
  end

  def save_result
    self.success? ? self.passed = true : self.passed = false

    save!
  end

  private

  def set_current_question
    self.current_question = next_question
  end

  def next_question
    if current_question.nil?
      test.questions.first
    else
      test.questions.order(:id).where('id > ?', current_question.id).first
    end
  end

  def correct_answer?(answer_ids)
    unless answer_ids.nil?
      correct_answers.ids.sort == answer_ids.map(&:to_i).sort
    end
  end

  def correct_answers
    current_question.answers.correct_answers
  end

  def set_deadline
    self.deadline = Time.now.advance(minutes: test.time_in_min) if test.time_in_min.present? 
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :confirmable

  has_many :created_tests, class_name: 'Test', foreign_key: 'author_id', dependent: :destroy
  
  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages

  has_many :user_badges, dependent: :destroy
  has_many :badges, through: :user_badges

  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }

  def find_test_by_level(level)
    tests.where(level: level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController
  before_action :find_test_passage

  def create
    result = GistQuestionService.new(@test_passage.current_question).call

    if result.success?
      Gist.create!(question: @test_passage.current_question, url: result.url, author: current_user)

      redirect_to @test_passage, notice: view_context.link_to(t('.notice'), result.url, target: '_blank').html_safe
    end
  end

  private

  def find_test_passage
    @test_passage = TestPassage.find(params[:test_passage_id])
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController

  def index
    @tests = Test.all
  end

  def start
    @test = Test.find(params[:id])

    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_year
    Date.current.year
  end

  def github_url(author, repo)
    link_to "Github", "https://github.com/#{author}/#{repo}", target: "_blank"
  end

  def project_link
    if user_signed_in?
      if current_user.type == "Admin"
        link_to "Test Guru Admin", admin_tests_path, class: "navbar-brand"
      else
        link_to "Test Guru", authenticated_root_path, class: "navbar-brand"
      end
    else
      link_to "Test Guru", unauthenticated_root_path, class: "navbar-brand"
    end
  end

  def flash_class(key)
    case key.to_sym
    when :notice then "alert alert-info"
    when :success then "alert alert-success"
    when :error then "alert alert-error"
    when :alert then "alert alert-danger"
    end
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/gists_helper.rb
module GistsHelper
  def gist_hash(gist)
    gist.url.split('/').last
  end

  def gist_question_truncate(gist)
    gist.question.body.truncate(25)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.new_record?
      "Create New #{question.test.title} Questions"
    else
      "Edit #{question.test.title} Question"
    end
  end
end

app/helpers/tests_helper.rb
module TestsHelper
  def test_header(test)
    if test.new_record?
      "Create New Test"
    else
      "Edit '#{test.title}'"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <title>TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navigation' %>

    <div class="container">
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>

    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.present? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
    <h2><%= pluralize(resource.errors.count, 'error') %> found:</h2>

    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<div>
  <% flash.each do |key, message| %>
    <div class="<%= flash_class(key) %>" role="alert">
      <%= message.html_safe %>
    </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<footer>
  <p>
    <%= t('.year') %> <%= current_year %> ||
    <%= t('.author') %> Hanna ||
    <%= link_to t('.feedback'), feedbacks_path %> ||
    <%= github_url('NeskladAnya', 'test-guru') %> ||
    <%= link_to t('.project'), 'https://thinknetica.com/', target: "_blank" %>
  </p>
</footer>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <%= project_link %>
    <div class="nav-item">
      <% if user_signed_in? %>
        <% if current_user.type == "Admin" %>
          <%= link_to 'Gists', admin_gists_path %>
          <%= link_to t('.badges'), admin_badges_path %>
          <%= link_to t('.admin'), admin_tests_path %>
        <% else %>
          <%= link_to t('.badges'), badges_path %>
        <% end %>
        <%= link_to t('.tests'), tests_path %>
        <%= t('.welcome', first_name: current_user.first_name) %>! || 
        <%= link_to t('.log_out'), destroy_user_session_path, method: :delete %>
    </div>
    <% else %>
      <%= link_to t('.log_in'), new_user_session_path %> ||
      <%= link_to t('.sign_up'), new_user_registration_path %>
    <% end %>
  </div>
</nav>