config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path_names: { sign_in: :login, sign_out: :logout, sign_up: :signup }, controllers: {sessions: "sessions"}

  authenticated :user do
    root 'tests#index', as: :authenticated_root
  end

  unauthenticated :user do
    devise_scope :user do
      root 'sessions#new', as: :unauthenticated_root
    end
  end
  
  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[ show update ] do
    resources :gists, only: :create
    member do
      get :result
    end
  end

  resources :badges, only: :index

  namespace :admin do
    resources :gists, only: :index
    resources :badges, except: :show
    resources :tests do
      patch :update_inline, on: :member
      
      resources :questions, except: :index, shallow: true do
        resources :answers, shallow: true, except: :index
      end
    end
  end

  resources :feedbacks, only: %i[ index create ]

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :validate_number_of_answers, on: :create

  scope :correct_answers, -> { where(correct: true) }

  private
  
  def validate_number_of_answers
    errors.add(:answers_count, 'limit is 4') unless question.answers.count < 4
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController
  before_action :find_question, only: %i[ new create]
  before_action :set_answer, only: %i[ show edit update destroy ]

  def show
  end

  def new
    @answer = @question.answers.new
  end

  def edit
  end

  def create
    @answer = @question.answers.new(answer_params)

    if @answer.save
      redirect_to admin_answer_path(@answer)
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to admin_answer_path(@answer)
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to admin_question_path(@answer.question)
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/admin/answers/_answer.html.erb
<li>
  <%= answer.body %><br>
  <%= link_to t('actions.show'), admin_answer_path(answer) %>
  <%= link_to t('actions.edit'), edit_admin_answer_path(answer) %>
  <%= link_to t('actions.delete'),
              admin_answer_path(answer),
              method: :delete,
              data: { confirm: t('actions.confirm') } %>
</li>

app/views/admin/answers/_form.html.erb
<%= form_with model: [:admin, @question, @answer], local: true do |form| %>
  <%= render 'devise/shared/error_messages', resource: @answer %>

  <p>
    <%= form.label :body %>
    <%= form.text_area :body, id: :answer_body, rows: 7, cols: 60 %>
  </p>

  <p>
    <%= form.label :correct %>
    <%= form.check_box :correct, id: :answer_correct %>
  </p>

  <p><%= form.submit %></p>
<% end %>

app/views/admin/answers/edit.html.erb
<h1>Edit Answer</h1>

<p><%= @answer.question.body %></p>

<%= render 'form' %>

<%= link_to t('nav.back'), admin_question_path(@answer.question) %>

app/views/admin/answers/new.html.erb
<h1><%= t('.header') %></h1>

<p><%= @question.body %></p>

<%= render 'form' %>

<%= link_to t('nav.back'), admin_question_path(@question) %>

app/views/admin/answers/show.html.erb
<h1><%= t('.header') %></h1>

<p><%= @answer.question.body %></p>

<p>
  <b><%= t('.answer') %></b>
  <%= @answer.body %>
</p>

<p>
  <b><%= t('.correct') %></b>
  <%= @answer.correct %>
</p>

<%= link_to t('nav.back'), admin_question_path(@answer.question) %> |
<%= link_to t('nav.edit'), edit_admin_answer_path(@answer) %>