config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path_names: { sign_in: :login, sign_out: :logout, sign_up: :signup }, controllers: {sessions: "sessions"}

  authenticated :user do
    root 'tests#index', as: :authenticated_root
  end

  unauthenticated :user do
    devise_scope :user do
      root 'sessions#new', as: :unauthenticated_root
    end
  end
  
  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[ show update ] do
    resources :gists, only: :create
    member do
      get :result
    end
  end

  resources :badges, only: :index

  namespace :admin do
    resources :gists, only: :index
    resources :badges, except: :show
    resources :tests do
      patch :update_inline, on: :member
      
      resources :questions, except: :index, shallow: true do
        resources :answers, shallow: true, except: :index
      end
    end
  end

  resources :feedbacks, only: %i[ index create ]

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test 
  
  has_many :answers, dependent: :destroy

  validates :body, presence: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController
  before_action :find_test, only: %i[create new]
  before_action :find_question, only: %i[show edit update destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def new
    @question = @test.questions.new

    @question_test = Test.find(@question.test_id)
  end

  def create
    @question = @test.questions.new(question_params)

    if @question.save
      redirect_to admin_question_path(@question)
    else
      render :new
    end
  end

  def show
    @question_test = Test.find(@question.test_id)
  end

  def edit; end

  def update
    if @question.update(question_params)
      redirect_to admin_question_path(@question)
    else
      render :edit
    end
  end

  def destroy
    @question.destroy

    @question_test = Test.find(@question.test_id)
    redirect_to admin_test_path(@question_test)
  end

  private

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:body)
  end

  def rescue_with_question_not_found
    render plain: 'Question is not found'
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.new_record?
      "Create New #{question.test.title} Questions"
    else
      "Edit #{question.test.title} Question"
    end
  end
end

app/views/admin/questions/_form.html.erb
<%= form_with model: [:admin, @test, @question], local: true do |form| %>
  <%= render 'devise/shared/error_messages', resource: @question %>
  <p>
    <%= form.label :body %><br>
    <%= form.text_field :body %>
  </p><br>

  <p><%= form.submit %></p>
<% end %>

app/views/admin/questions/_question.html.erb
<tr>
  <td><%= question.body %></td>
  <td><%= link_to t('actions.show'), admin_question_path(question) %></td>
  <td><%= link_to t('actions.edit'), edit_admin_question_path(question) %></td>
  <td>
    <%= link_to t('actions.delete'), 
                admin_question_path(question),
                method: :delete,
                data: {confirm: t('actions.confirm')} %>
  </td>
</tr>

app/views/admin/questions/edit.html.erb
<h1><%= question_header(@question) %></h1>

<%= render 'form' %>

<%= link_to t('nav.back'), admin_question_path(@question) %>

app/views/admin/questions/new.html.erb
<h1><%= t('.header', test: @question.test.title) %></h1>

<%= render 'form' %>

<%= link_to t('nav.back'), admin_test_path(@question.test) %>

app/views/admin/questions/show.html.erb
<h1><%= t('.header') %></h1>

<p><%= @question.body %></p>

<h2><%= t('.answers') %></h2>

<%= link_to t('.new_answer'), new_admin_question_answer_path(@question) %>

<ol>
  <%= render @question.answers%>
</ol>

<%= link_to t('nav.back'), admin_test_path(@question_test) %> |
<%= link_to t('nav.edit'), edit_admin_question_path(@question) %>